In [5]:
import numpy as np

In [18]:
x= np.random.randint(1,100,size=10) #1 부터 100까지중 10개 랜덤 추출(중복허용)
x

array([88, 15,  7, 86, 91, 14,  6, 57, 28, 90])

In [23]:
x_mask = x % 2 == 0 #x_mask에 x가 짝수인지 가리는 boolean_mask 할당

In [24]:
x[x_mask] #x인덱싱에 x_mask를 넣는 것으로 True인것만 나오는 모습

array([88, 86, 14,  6, 28, 90])

In [25]:
x[x%2 ==0] #바로 인덱싱해도 문제 x

array([88, 86, 14,  6, 28, 90])

In [30]:
x[(x%2==0) & (x>50)] #조건에 괄호를 치고 다중조건 사용 가능

array([88, 86, 90])

In [31]:
x[(x%2==0) | (x>50)] 

array([88, 86, 91, 14,  6, 57, 28, 90])

In [32]:
x%2==0 #boolean type으로 이루어져 있음

array([ True, False, False,  True, False,  True,  True, False,  True,
        True])

In [34]:
(x%2==0).astype(int) #int type으로 변경 가능 
    #머신러닝에서 onehot encoding으로 변환 시 자주 사용

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1])

In [36]:
x[(x%2==0).astype(int)] #onehot encoding 후에는 동일하게 사용 불가

array([15, 88, 88, 15, 88, 15, 15, 88, 15, 15])

In [37]:
np.sum(x%2==0) #True=1 False=0이기 때문에 개수 세는 데 용이

6