In [2]:
import numpy as np

In [3]:
x=np.arange(10) # 0이상 부터 10 미만 까지의 array를 생성한다
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x[0],x[9],x[-1],x[-10] #x의 0번째 인덱스, 9번째 인덱스, 끝에서 첫번째 인덱스(끝에서 하면 첫번째를 부르려면 -10이되니 count에 주의)

(0, 9, 9, 0)

In [6]:
x=np.arange(10).reshape(2,5) #x를 모양이 (2,5)인 2차원 배열로 생성
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
x.shape, x.ndim, x.dtype, x.size # x의 모양, x의 차원, x의 데이터타입, x의 크기
#데이터를 전처리하기전 가장 먼저 알아야 할 4인방

((2, 5), 2, dtype('int32'), 10)

In [8]:
x[0], x[1] #인덱싱을 할 때 차원이 준다.

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), 2, 2)

In [9]:
x[0][2], x[0,2] #인덱싱을 두번 했더니 0차원 까지 된 모습 
# ',' 로 인덱싱 하는 것은 list에서는 불가능한 방식 numpy 에서는 , 사용 추천 

(2, 2)

In [12]:
x= np.arange(36).reshape(3,2,6) #x를 모양이 (3,2,6)인 3차원 배열로 생성
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [14]:
x[0] # 결과는 2차원 array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [16]:
x[2,1] #결과는 1차원 array

array([30, 31, 32, 33, 34, 35])

In [17]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

1차원 행렬 슬라이싱

In [18]:
a[1:5] #결과는 1차원 array 원본과 차원에서는 차이가 없음

array([1, 2, 3, 4])

In [19]:
a[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a[:5]

array([0, 1, 2, 3, 4])

In [22]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a[::3] #몇 번씩 건너 뛰는 지(step) 명시 가능 

array([0, 3, 6, 9])

In [25]:
a[1::3], a[-1::3]

array([1, 4, 7])

In [29]:
a[3::], a[3::-1]

(array([3, 4, 5, 6, 7, 8, 9]), array([3, 2, 1, 0]))

2차원 행렬 슬라이싱

In [30]:
y = [[0, 4],
     [5, 6, 7, 8, 9, 10, 11, 12],
     [12, 13, 14, 15]]
y

[[0, 4], [5, 6, 7, 8, 9, 10, 11, 12], [12, 13, 14, 15]]

In [32]:
y[2] #1차원 array

[12, 13, 14, 15]

In [35]:
y[0:2] #2차원 array

[[0, 4], [5, 6, 7, 8, 9, 10, 11, 12]]

In [36]:
x = np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#이 때 특정 구역만 가져오려면?
## [[6, 7, 8],
#  [11, 12, 13]]

In [45]:
x[1:,1:4] #먼저 x[1],x[2]를 합친 x[1:]을 가져오고, 가져오려는 부분의 인덱싱 진행

array([[ 6,  7,  8],
       [11, 12, 13]])

In [47]:
x[1,:3] #앞은 인덱싱, 뒤는 슬라이싱 -> 1차원 array

array([5, 6, 7])

In [51]:
x[:2,1] #x[:2][1]와 다르다

array([1, 6])

In [52]:
x[:2][1]

array([5, 6, 7, 8, 9])

다차원 array slicing

In [53]:
arr2 = np.arange(1,17).reshape(4,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [56]:
#array([[ 10, 11,  12],
#       [14, 15, 16]]) 하려면?
arr2[2:][1:] #[ ][ ]으로는 안됨  슬라이싱을 두번 진행하여 1차원 array   

array([[13, 14, 15, 16]])

In [57]:
arr2[2:,1:] #슬라이싱을 한 번 진행하여 2차원 array 
#각 차원 별로 slicing이 가능한 , 사용 권장

array([[10, 11, 12],
       [14, 15, 16]])

3차원 텐서 슬라이싱

In [58]:
x= np.arange(54).reshape(2,9,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [60]:
# 다음을 slicing 해보자
# [[[30, 31, 32],
#  [33, 34, 35]]]
x[1:,1:3] #[]가 아닌 , 활용으로 3차원 유지 슬라이싱

array([[[30, 31, 32],
        [33, 34, 35]]])

In [64]:
x[1,1:3, :] #앞에 인덱싱을 추가하면 결과는 2차원

array([[30, 31, 32],
       [33, 34, 35]])

In [ ]:
# 도전]
# 다음의 결과 만드려면?
# [[ 2,  5,  8, 11, 14, 17, 20, 23, 26],
#  [29, 32, 35, 38, 41, 44, 47, 50, 53]]  <- 2차원

In [67]:
x[:,:,2] #3차원만 슬라이싱을 진행하며 차원을 줄여야 한다

array([[ 2,  5,  8, 11, 14, 17, 20, 23, 26],
       [29, 32, 35, 38, 41, 44, 47, 50, 53]])

In [68]:
x[:,:,2:] #:를 붙이면 3차원을 유지가능

array([[[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17],
        [20],
        [23],
        [26]],

       [[29],
        [32],
        [35],
        [38],
        [41],
        [44],
        [47],
        [50],
        [53]]])