In [1]:
import numpy as np

ndarray의 기본연산,기본함수

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.arange(0, 150, 10).reshape(3, 5)
y2 = np.random.rand(15).reshape(3, 5)
y3 = np.arange(15).reshape(5, 3)

In [3]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
y

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140]])

In [5]:
y2

array([[0.81567356, 0.32721672, 0.0906572 , 0.00723005, 0.34293   ],
       [0.20345617, 0.40169821, 0.07948816, 0.49304946, 0.46400982],
       [0.31747887, 0.63386921, 0.28175994, 0.46858296, 0.44460131]])

In [6]:
y3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

array간 연산자

In [8]:
a= [10,20,30,40]
a

[10, 20, 30, 40]

In [9]:
b=2

In [10]:
c=[100,200,300,400]

In [12]:
a*b #a라는 list를 두번 반복

[10, 20, 30, 40, 10, 20, 30, 40]

In [15]:
a+c #a와 c의 원소를 더하는게 아닌 원소를 순서대로 배치

[10, 20, 30, 40, 100, 200, 300, 400]

In [16]:
x+y #리스트와는 달리 같은 위치의 원소끼리 연산 실행

array([[  0,  11,  22,  33,  44],
       [ 55,  66,  77,  88,  99],
       [110, 121, 132, 143, 154]])

In [17]:
x-y

array([[   0,   -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72,  -81],
       [ -90,  -99, -108, -117, -126]])

In [18]:
x*y

array([[   0,   10,   40,   90,  160],
       [ 250,  360,  490,  640,  810],
       [1000, 1210, 1440, 1690, 1960]])

In [19]:
x/y #y에 0이 있어서 nan값 생성 오류가 아님

C:\Users\user\AppData\Local\Temp\ipykernel_17764\1719814938.py:1: RuntimeWarning: invalid value encountered in true_divide
  x/y


array([[nan, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1]])

In [20]:
x + 10  #array에 스칼라 값을 연산시키면 모든원소에 연산 실시

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
10 + x #교환법칙 적용

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
np.array(10)

array(10)

In [23]:
x+np.array(10) #np.array(10)의 shape가 ()이니까 스칼라와 동일하게 연산

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
x + np.array([10]) # 동일한 결과

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
x + [10]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
x + (10,)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

기본 함수

In [27]:
np.add(x,y)

array([[  0,  11,  22,  33,  44],
       [ 55,  66,  77,  88,  99],
       [110, 121, 132, 143, 154]])

In [28]:
x+y #위와 동일

array([[  0,  11,  22,  33,  44],
       [ 55,  66,  77,  88,  99],
       [110, 121, 132, 143, 154]])

In [29]:
# np.add(x,y3) #shape이 달라서 안됨 broacast 시켜야됨

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [31]:
np.subtract(x,y) #x-y

array([[   0,   -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72,  -81],
       [ -90,  -99, -108, -117, -126]])

In [32]:
np.multiply(x,y) #x*y

array([[   0,   10,   40,   90,  160],
       [ 250,  360,  490,  640,  810],
       [1000, 1210, 1440, 1690, 1960]])

In [33]:
np.divide(x,y) #x/y

C:\Users\user\AppData\Local\Temp\ipykernel_17764\3307111101.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.divide(x,y) #x/y


array([[nan, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1]])

shape이 다른 경우 연산

In [34]:
a= np.arange(12).reshape(4,3)
b=np.arange(100,103)

In [35]:
a,b

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([100, 101, 102]))

In [36]:
a+b #a와 b의 shape이 다르지만 맨 마지막의 차원값이 일치하면 연산을 할수 있다

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [37]:
a.shape,b.shape

((4, 3), (3,))

In [38]:
c= np.arange(100,104)
c

array([100, 101, 102, 103])

In [39]:
# a+c #에러

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

통계함수

In [40]:
y2

array([[0.81567356, 0.32721672, 0.0906572 , 0.00723005, 0.34293   ],
       [0.20345617, 0.40169821, 0.07948816, 0.49304946, 0.46400982],
       [0.31747887, 0.63386921, 0.28175994, 0.46858296, 0.44460131]])

In [41]:
np.mean(y2),y2.mean()

(0.35811344303746384, 0.35811344303746384)

In [42]:
np.max(y),y.max()

(140, 140)

In [43]:
np.min(y),y.min()

(0, 0)

In [48]:
np.argmax(y2) #index 14번째의 값이 가장크다

0

In [50]:
np.argmin(y2) #index 3번째의 값이 가장작다

3

In [51]:
np.var(y), np.std(y),np.median(y) #분산, 표준편차, 중앙값

(1866.6666666666667, 43.20493798938573, 70.0)

In [52]:
np.cumsum(y2) #누적함수 -> 피보나치 수열 느낌

array([0.81567356, 1.14289028, 1.23354748, 1.24077753, 1.58370754,
       1.7871637 , 2.18886191, 2.26835008, 2.76139954, 3.22540937,
       3.54288823, 4.17675745, 4.45851738, 4.92710034, 5.37170165])

In [53]:
z = np.random.randn(10)
z

array([ 0.33860609,  1.81554942, -1.22391618,  0.45967896, -1.11919486,
       -0.15875253,  1.10866559, -0.68159281,  0.42867084,  1.8040716 ])

In [54]:
z>0 , z<0 #조건에 해당하면 True, 아니면 False

(array([ True,  True, False,  True, False, False,  True, False,  True,
         True]),
 array([False, False,  True, False,  True,  True, False,  True, False,
        False]))

In [55]:
5+True,5-True,5+False #True는 연산에 참여하면 1로 계산되고 False는 0으로 계산된다

(6, 4, 5)

In [56]:
np.sum(z>0) #0이 넘는 z값의 개수

6

In [58]:
np.any(z>0) #z 중 무언가는 0보다 크다 -> True

True

In [59]:
np.all(z>0) # z는 전부 0보다 크다 -> False

False

In [60]:
np.all(z!=0) # z는 전부 0이 아니다 -> True

True

In [61]:
np.where(z>0, z, 0) #z에서 0보다 큰거는 그대로 두고 그렇지 않은 것은 0으로

array([0.33860609, 1.81554942, 0.        , 0.45967896, 0.        ,
       0.        , 1.10866559, 0.        , 0.42867084, 1.8040716 ])