In [1]:
import numpy as np

In [6]:
x1 = np.arange(15)
x1, x1.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]), 1)

In [4]:
np.sum(x1) #np.sum에는 axis의 default가 None이다.

105

In [9]:
np.sum(x1, axis=0)  #현재 x1은 1차원 이므로 0차원 단위의 연산 밖에 할수 없다.

105

In [12]:
x2 = x1.reshape(3,5)
x2,x2.ndim

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2)

In [13]:
np.sum(x2) #전체 데이터 대상 연산, axis=None

105

In [18]:
np.sum(x2,axis=0),np.sum(x2,axis=1) #2차원에서는 차원에대한 연산을 두 방향 으로 할 수 있다.

(array([15, 18, 21, 24, 27]), array([10, 35, 60]))

In [ ]:
#ndim=2 , shape = (x,y) 일때, np.sum(x2,axis=0)을 실행하면 shape[0]인 x의 방향으로
#연산을 하여 결과 shape는 (y,)가 된다.

In [ ]:
#ndim=2 , shape = (x,y) 일때, np.sum(x2,axis=1)을 실행하면 shape[1]인 y의 방향으로
#연산을 하여 결과 shape는 (x,)가 된다.

In [21]:
x3= np.arange(24).reshape(3,4,2)
x3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [22]:
np.sum(x3)

276

In [23]:
np.sum(x3, axis=0) #3차원에서 -> 2차원 , shape (3,4,2) -> (4,2)

array([[24, 27],
       [30, 33],
       [36, 39],
       [42, 45]])

In [24]:
np.sum(x3, axis=1) #3차원에서 -> 2차원 , shape (3,4,2) -> (3,2)

array([[12, 16],
       [44, 48],
       [76, 80]])

In [25]:
np.sum(x3, axis=2) #3차원에서 -> 2차원 , shape (3,4,2) -> (3,4)

array([[ 1,  5,  9, 13],
       [17, 21, 25, 29],
       [33, 37, 41, 45]])

In [26]:
np.sum(x3, axis=(0,1))#3차원에서 -> 1차원 , shape (3,4,2) -> (2,)

array([132, 144])

In [27]:
np.sum(x3, axis=(1,2))#3차원에서 -> 1차원 , shape (3,4,2) -> (3,)

array([ 28,  92, 156])

In [28]:
np.sum(x3, axis=(0,2))#3차원에서 -> 1차원 , shape (3,4,2) -> (4,)

array([51, 63, 75, 87])