In [52]:
import numpy as np

In [53]:
x=np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [54]:
x.ravel(),np.ravel(x) #객체의 메소드, 자체 함수(map, filter, reduce 사용가능)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]))

In [55]:
x.ravel(order="C"),np.ravel(x,order="C") # 1차원 방향으로 펼쳐짐

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]))

In [56]:
x.ravel(order="F"),np.ravel(x,order="F") # 2차원 방향으로 펼쳐짐

(array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14]),
 array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14]))

In [57]:
y = np.arange(15).reshape(3,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
y.flatten()# flatten은 copy를 생성하여 복사본을 반환시킴

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
y.flatten(order="F")# 2차원 방향으로 펼쳐짐

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [60]:
temp = x.ravel()
temp,x

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]))

In [61]:
temp[0]= 100
temp, x #temp와 x 둘다 100이 들어간 모습

(array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14]),
 array([[100,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14]]))

In [62]:
temp = y.flatten()
temp, y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]))

In [63]:
temp[0] = 100
temp, y #temp의 0번쨰 인덱스 값을 바꾸어도 참조한 y에는 변화가 없는 모습

(array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]))

reshape 다른 차원으로 변경

In [64]:
x2 =np.arange(36)
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [65]:
x2.shape

(36,)

In [66]:
x2.reshape(6,6) #reshape하는 차원의 size와 원본의 size가 동일해야 실행가능

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [67]:
# x2.reshape(6,5) #에러

In [68]:
x2.reshape(6,-1) #-1을 적으면 다른 차원에 할당한 수와 size를 비교하여 적절한 숫자를 배치

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [69]:
# x2.reshape(6,-1,-1) #-1을 복수로 사용하는 것은 불가능

In [70]:
x2.reshape(3,-1,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [71]:
#직접 shape에 값 입력  -> 원본 변화
x2.shape = 3,-1,4
x2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

차원 확장, 제거

In [72]:
x3 = x3.reshape(6,1)
x3 #2차원

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [73]:
x3.shape, x3.ndim, x3.size

((6, 1), 2, 6)

In [74]:
x3.squeeze() #2차원에서 1차원으로 바뀜

array([0, 1, 2, 3, 4, 5])

In [75]:
x4 = np.arange(4).reshape((2,1,2))
x4

array([[[0, 1]],

       [[2, 3]]])

In [76]:
# x4를 squeeze 하면?
# (2,1,2) -> (2,2)

In [77]:
x4.squeeze()

array([[0, 1],
       [2, 3]])

In [78]:
x5 = np.arange(3)
x5 ,x5.shape

(array([0, 1, 2]), (3,))

In [79]:
y5 = np.expand_dims(x5,0) #0번째 axis() 에 새로운 차원 삽입
y5,y5.shape

(array([[0, 1, 2]]), (1, 3))

In [80]:
x6 = np.arange(4).reshape((2,2))
x6,x6.shape

(array([[0, 1],
        [2, 3]]),
 (2, 2))

In [81]:
y6 = np.expand_dims(x6,1)
y6,y6.shape

(array([[[0, 1]],
 
        [[2, 3]]]),
 (2, 1, 2))

In [82]:
y6.squeeze() #1을추가한 차원을 없애서 x6과 동일

array([[0, 1],
       [2, 3]])

In [83]:
y7 = np.expand_dims(x6,-1) #마지막에 차원 추가하기 -1
y7,y7.shape

(array([[[0],
         [1]],
 
        [[2],
         [3]]]),
 (2, 2, 1))

전치행렬

In [84]:
a = np.arange(15).reshape(3,5)
a , a.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 (3, 5))

In [85]:
np.transpose(a),a.T #2차원에서 행렬이 바뀐것을 확인 가능

(array([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]]),
 array([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]]))

In [86]:
np.swapaxes(a,0,1) # a 의 0번째 (차원)과 1번째 차원 축을 바꾼다

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [87]:
#내적 구하기
np.dot(a.T, a)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [88]:
b=np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [89]:
b.T 

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [90]:
np.transpose(b)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [91]:
#transpose() 는 바꾸고 싶은 axis 축의 순서 지정 가능!
np.transpose(b, (2,1,0)) #(2,3,4) -> (4,3,2) 0은 2로 1은 1로 2는 0으로

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [92]:
np.transpose(b, (1,0,2)) #(2,3,4) -> (3,2,4) 0은 1로 1은 0로 2는 2로

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [93]:
np.swapaxes(b,0,2) # (2,3,4) -> (4,3,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])